### ISSUE TITLE
Transform normals with inverse transpose

### ISSUE THREAD

**Issue by szellmann** [ingowald/pbrt-parser#14]
Should this here: https://github.com/ingowald/pbrt-parser/blob/master/pbrtParser/impl/semantic/Geometry.cpp#L97 say xfmNormal() instead of xfmVector()? (I'm not a 100% sure, I just stumbled upon it while inspecting the code and haven't verified it.)

**Comment by ingowald** [comment]
good catch! Probably never seen any artifacts because none of my models have any non-uniform scales (in which case xfmNormal and xfmVector will be the same) ... but you're certainly right!

**Comment by ingowald** [comment]
fixed. Thank you!
