### ISSUE TITLE
Default values for material properties

### ISSUE THREAD

**Issue by szellmann** [ingowald/pbrt-parser#17]
Currently the default values for the material properties (kd,ks,roughness,eta etc.) differ from [the specs](https://www.pbrt.org/fileformat-v3.html). Especially with the glass material this is problematic because the current default values violate the energy conservation property of the BSDF, and it seems like every pbrt-v3-scenes model just uses the default glass material. Would you accept a PR with the default values adjusted to the specs? Or would this interfere with some personal setup that you're using and don't want to be changed?

**Comment by ingowald** [comment]
Would be happy to see it!

**Comment by ingowald** [comment]
AFAIU that was fixed in the latest merge
