### ISSUE TITLE
Semantic parser crashes if material refers to non-existent texture

### ISSUE THREAD

**Issue by szellmann** [ingowald/pbrt-parser#19]
Sorry, lot's of noise :-)

If the pbrt file erroneously refers to a non-existent texture in a material, the semantic parser simply crashes [here](https://github.com/ingowald/pbrt-parser/blob/master/pbrtParser/impl/semantic/Textures.cpp#L104) due to `Material:: getParamTexture()` returning a `nullptr` [here](https://github.com/ingowald/pbrt-parser/blob/master/pbrtParser/impl/semantic/Materials.cpp#L231). You can repro with `pbrt-v3-scenes/measure-one/frame120.pbrt`. A possible fix would be to test if `!p->texture` [right here](https://github.com/ingowald/pbrt-parser/blob/master/pbrtParser/impl/syntactic/Scene.cpp#L306) and in that case throw an exception (that can be caught and maybe handled at application level).

**Comment by ingowald** [comment]
The other functions seem to handle "does not exist" with returning null handles rather than exceptions, so I'm going to look whether i can fix it this way first.

**Comment by szellmann** [comment]
Yes wasn’t sure about this and also had seen the other functions, this is why I didn’t submit a PR but rather created an issue.
