### ISSUE TITLE
VS specific errors

### ISSUE THREAD

**Issue by Chrjstoph** [ingowald/pbrt-parser#3]
Hi again,

I have begun loading of Materials and included 
#include "pbrt/Parser.h"
in my Material header.

Compiling fails:

Its easily solved but maybe you want to know.

Error	304	error C4996: 'getenv': This function or variable may be unsafe. Consider using _dupenv_s instead. To disable deprecation, use _CRT_SECURE_NO_WARNINGS. See online help for details.	f:\vr\pbrt-parser\ospcommon\common.h	147

**Comment by ingowald** [comment]
if you send me a push request for this fix i'd be happy to take it!

**Comment by Chrjstoph** [comment]
Well, I have cheated and used the MACRO.

If I come around to it, I will notify you.
