### ISSUE TITLE
LookAt handedness

### ISSUE THREAD

**Issue by kennyalive** [ingowald/pbrt-parser#31]
Pbrt uses left-handed coordinate system and it constructs LookAt frame with vectors that also form left-handed coordinate system.
The library constructs these vectors differently. If we assume left-handed coordinate system (and corresponding rules for cross product) then the frame constructed by LookAt (until inversion) will be right handed. And if we assume right-handed rules than the resulting frame will be left-handed. Is it indended behavior? If not it would be nice to construct LookAt transform the same way as pbrt does.

**Comment by ingowald** [comment]
Hm. Admittedly so far I took the shortcut of just "making it match" the right-handed renderers I'm usually working with; but I also do see the argument that as a pure parser library this flipping should be done _after_ parsing (by the renderer). If you do want to change this, I'd be happy to merge it in.
