### ISSUE TITLE
Build error on Mac OS

### ISSUE THREAD

**Issue by zhaoyangyang316** [ingowald/pbrt-parser#48]
Hi, 

I was trying to build pbrt-parser on Mac OS and I got the following errors:

> 
> /Users/yangyangzhao/codes/pbrt-parser/pbrtParser/include/pbrtParser/math.h:81:37: error: expected member name or ';' after declaration specifiers
>       explicit vec2f(float v) : x{v}, y{v} { }
>                                     ^
> /Users/yangyangzhao/codes/pbrt-parser/pbrtParser/include/pbrtParser/math.h:81:34: error: expected '('
>       explicit vec2f(float v) : x{v}, y{v} { }
>                                  ^
> /Users/yangyangzhao/codes/pbrt-parser/pbrtParser/include/pbrtParser/math.h:81:36: error: expected ';' after expression
>       explicit vec2f(float v) : x{v}, y{v} { }

I feel like I missed one vec lib dependency..

Cheers
Yangyang

**Comment by szellmann** [comment]
Hey,

I can repro, on macOS 11.4. For me, by default the project builds in C++03 mode, and that header uses features from C++11.

An immediate fix you could use is to set compiler flags accordingly when configuring the project:
```cmake .. -DCMAKE_CXX_FLAGS=std=c++11```

On our end, we (@ingowald) should probably add
```
set(CMAKE_CXX_STANDARD 11)
set(CMAKE_CXX_STANDARD_REQUIRED ON)
```
to the main `CMakeLists.txt` file.

Cheers,
Stefan

**Comment by ingowald** [comment]
Yes that 11 standard should be on. Can you push fix or send PR?

**Comment by szellmann** [comment]
https://github.com/ingowald/pbrt-parser/pull/49

**Comment by zhaoyangyang316** [comment]
> Hey,
> 
> I can repro, on macOS 11.4. For me, by default the project builds in C++03 mode, and that header uses features from C++11.
> 
> An immediate fix you could use is to set compiler flags accordingly when configuring the project: `cmake .. -DCMAKE_CXX_FLAGS=std=c++11`
> 
> On our end, we (@ingowald) should probably add
> 
> ```
> set(CMAKE_CXX_STANDARD 11)
> set(CMAKE_CXX_STANDARD_REQUIRED ON)
> ```
> 
> to the main `CMakeLists.txt` file.
> 
> Cheers, Stefan

thanks, that fixed the problem!

cheers
Yangyang
