### ISSUE TITLE
san miguel chair transformations

### ISSUE THREAD

**Issue by Chrjstoph** [ingowald/pbrt-parser#6]
Can you replicate those transform errors when parsing san miguel?

![sanmiguelchaors](https://cloud.githubusercontent.com/assets/6479196/22737323/ec72351a-ee02-11e6-8e61-12247027a1fc.PNG)

**Comment by ingowald** [comment]
Well; I don't know what view that is, but here's three pics of sanmiguel 
that i think show transforms are working OK.

(all three rendered using ospray, using the output of pbrt2rivl from the 
devel/ branch).

Materials still missing (ospray can't properly handle the pbrt 
materials, yet), but the transforms look OK to me.

**Comment by Chrjstoph** [comment]
I cannot find any attachments.

The chairs with thr round back rest are all off.
I just dont know why, yet.

**Comment by ingowald** [comment]
should all be working in latest version
